server:
  port: 8888
  context-path: /

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://120.24.189.68:3306/Protocol
    username: root
    password: root
  jpa:
    hibernate.ddl-auto: update
    show-sql: false
  devtools:
    restart:
      enable: true
      additional-paths: src/main/java